apiVersion: v1
kind: Service
metadata:
  name: sampleserver
  namespace: sample
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 3000
  selector:
    app: sampleserver
  type: ClusterIP